
export const SUBMIT_FORM = "FORM/SUBMIT_FORM";

export const FETCH_LOADING = "APP/FETCH_LOADING";
export const FETCH_FAILED = "APP/FETCH_FAILED";
export const ADD_FETCH_DATA = "APP/ADD_FETCH_DATA";

export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const PROMOS_LOADING = "PROMOS_LOADING";
export const ADD_PROMOS = "ADD_PROMOS";
export const PROMOS_FAILED = "PROMOS_FAILED";
